### PR TITLE
Remove jwst-workshop.yml file since it doesn't work on Linux

### PR DESCRIPTION
**Pull request by astrofrog**
The current environment file has too many packages and too specific versions to be compatible on all platforms and fails on Linux. I think it would be better to go with a minimal environment file like the one I'm using for mybinder, which only gives the dependencies we actually need for the workshop.

However, please let me know if packages are missing from this! (before 8:15am)

Unless there are any objections, I will need to merge this to make sure the installation instructions work for everyone.

### CODE REVIEW

**Comment by nden** [comment]
Please add if possible

asdf >=1.2.1
gwcs >= 0.6

**Comment by astrofrog** [comment]
@nden - done. Can you or someone else with admin rights enable Travis on this repository? (I will add the Travis config file). That way I can make sure the file works fine on Linux/Mac. I don't have admin privileges for this repo so I can't flick the switch on Travis.

**Comment by nden** [comment]
@astrofrog I flipped the switch on travis. Push to to try it out.

**Comment by astrofrog** [comment]
@nden - thanks! Let's see if this works.

**Comment by astrofrog** [comment]
@nden - it doesn't look flipped when I checked - just to check, did you enable it on your fork by mistake? (I do that all the time...)

**Comment by nden** [comment]
OK, it started

**Comment by astrofrog** [comment]
@nden - asdf and gwcs don't have the required versions on linux (e.g. the latest asdf is 1.0.3). Shall I remove the version requirement, or make them be installed from pip instead? (can be done in an environment file)

**Comment by astrofrog** [comment]
```
(dev) eleven:~ tom$ conda search --plat linux-64 asdf
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
asdf                         1.0.2               np110py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.2               np110py34_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.2               np110py35_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.2               np111py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.2               np111py35_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.3               np110py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.3               np110py34_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.3               np110py35_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.3               np111py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.3               np111py35_0  http://ssb.stsci.edu/astroconda/linux-64 
asdf-standard                1.0.0                    py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.0                    py34_0  http://ssb.stsci.edu/astroconda/linux-64 
                             1.0.0                    py35_0  http://ssb.stsci.edu/astroconda/linux-64 
(dev) eleven:~ tom$ conda search --plat linux-64 gwcs
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
gwcs                         0.5                 np110py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.5                 np110py34_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.5                 np110py35_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.5.1               np110py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.5.1               np110py34_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.5.1               np110py35_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.6rc1              np110py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.6rc1              np110py34_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.6rc1              np110py35_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.6rc1              np111py27_0  http://ssb.stsci.edu/astroconda/linux-64 
                             0.6rc1              np111py35_0  http://ssb.stsci.edu/astroconda/linux-64 
```

**Comment by nden** [comment]
Ir should be OK to remove the version requirement and then later update.
If this doesn't work we can skip them and will provide instructions on how to install them from github.

**Comment by astrofrog** [comment]
Passing so I'll merge, if anyone wants to add more packages, please do it via a PR so the tests run

**Comment by pllim** [comment]
> (dev) eleven

Stranger Things fan?

**Pull request merged**
