### PR TITLE
Try testing Windows environment file

### PR DESCRIPTION
**Pull request by astrofrog**
Can someone enable AppVeyor for this repo, just to check if this does the trick? (@nden?)

### CODE REVIEW

**Comment by jhunkeler** [comment]
From environment.yml:

```
channels:
  - http://ssb.stsci.edu/astroconda
```

This can't work on Windows because http://ssb.stsci.edu/astroconda/win-[32|64] does not exist. There is no Windows support.

**Comment by astrofrog** [comment]
@jhunkeler - I already removed that line though

**Comment by jhunkeler** [comment]
Yeah, I know. I'm sorry I accidentally copied and pasted and hit "comment".

My reply was supposed to be: "Sure I'll activate appveyor for you, hold on"

**Comment by astrofrog** [comment]
@jhunkeler - @nden already did, so all good :)

**Comment by jhunkeler** [comment]
Ha!

Definitely Tuesday...

EDIT: It isn't Monday 💃

**Comment by astrofrog** [comment]
It's Tuesday! 😆

**Pull request merged**
