### PR TITLE
Added glue at least 0.9.1 to environment.yml

### PR DESCRIPTION
**Pull request by pllim**
@astrofrog , trying this again based on your feedback.

### CODE REVIEW

**Comment by astrofrog** [comment]
I decided to add all dependencies in one go in https://github.com/spacetelescope/JWSTUserTraining2016/commit/464f621b761764edc459495ecddde4d1b9da1c8f

**Comment by pllim** [comment]
Ahaha. Okay. p.s. Don't you ever sleep?!

**Comment by astrofrog** [comment]
@pllim - well, I'm trying not to, but the jet lag is making it hard. I'm at STScI this week! ;)

**Comment by pllim** [comment]
Ah. Of course! Good luck. Maybe the excitement of USA election on news channels will keep you awake. :wink:

**Comment by astrofrog** [comment]
😱

**Pull request closed without merging**
