### PR TITLE
Add advanced tables notebook

### PR DESCRIPTION
**Pull request by taldcroft**
Making this PR for big-picture review.  The goal was to cover most of the topics in the "Implementation Features" slide, but there may be enough material already.

If I can get this looking OK with nbpresent I will plan to do this as a talk with discrete slides, with no plan for exercises.

cc: @eteq

### CODE REVIEW

**Comment by larrybradley** [comment]
Is this ready to be merged?

**Comment by eteq** [comment]
@taldcroft - re: "big picture", looks good. A few specific bits:
- "Could be similar to JWST post-image processing workflow"  In fact it _is_: this is used in `photutils`, which is what will be driving the data analysis tools for photometry using JWST imagers.  And in fact we need to solve _exactly_ this problem for constructing models of the JWST PSF from images.  So this is a great demonstration of something we're planning to do but just haven't finished yet.
- I'd suggest you do the QTable stuff _first_, as that's the most likely place where people will see the point, without delving into the weeds.

**Comment by taldcroft** [comment]
It might be worth merging this now.  I'm going to be on travel / busy all day tomorrow, so probably better to at least have something in the repo for now.  I can look into using QTable first but it will take some rework of the flow.

**Comment by pllim** [comment]
OK, merging.

**Pull request merged**
